### ISSUE TITLE
CoD MWR can't export VoiceOvers (ENG) of Pak files.

### ISSUE THREAD

**Issue by TuxprOd** [Scobalula/Rottweiler#1]
Hi,

I guess all is in the title, i tried many FastFiles into my directory of MWR.

Of course, I can export basic sounds of weapons, ambiant sounds, deaths sounds... but not the voice overs.

I mean by voiceovers, the announcer who say for example "Enemy UAV is up" something like that.

I tried to load this file : "eng_code_post_gfx_mp.ff" because normaly this file contain the path of sounds who are located into the .pak files, but i don't get any sounds in the list.

Can you tell me why it doesn't work ?

Regards,

** ENG: english game version.

**Comment by Scobalula** [comment]
It can only export loaded audio. Try Greyhound in-game (check my repos), otherwise I have moved on from some of these projects so I don't have time to do further research on how they properly package non-loaded audio.
